# Generated by Django 5.0.6 on 2024-07-02 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail_imap_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mail_login',
        ),
        migrations.CreateModel(
            name='PrivateOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_login', models.EmailField(max_length=150)),
                ('mail_password_imap', models.CharField(max_length=200)),
                ('gmail_login', models.EmailField(max_length=150)),
                ('gmail_password_imap', models.CharField(max_length=200)),
                ('yandex_login', models.EmailField(max_length=150)),
                ('yandex_pssword_imap', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_office', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
