# Generated by Django 5.0.6 on 2024-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_mail_imap_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateoffice',
            name='gmail_login',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='privateoffice',
            name='gmail_password_imap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='privateoffice',
            name='mail_login',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='privateoffice',
            name='mail_password_imap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='privateoffice',
            name='yandex_login',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='privateoffice',
            name='yandex_pssword_imap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
