# Generated by Django 5.0.6 on 2024-07-02 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_privateoffice_gmail_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateoffice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_office', to=settings.AUTH_USER_MODEL),
        ),
    ]
